name: GitHub Self-hosted runner deployment standalone container apps
        
on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    deploy-environment:
        runs-on: 'ubuntu-latest'
        env:
          TerraformWorkingDirectory: 'src/infra/terraform/runner-infra'
          StateStoreContainerName: 'tfstate'
          StateStoreFilename: 'environment.tfstate'
        outputs:
          resourceGroupName: ${{ steps.vnetInfo.outputs.resourceGroupName }}
          runnerSubnetId: ${{ steps.vnetInfo.outputs.runnerSubnetId }}
        steps:
            - uses: actions/checkout@v3
            
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_wrapper: false
            
            - name: Azure login
              uses: azure/login@v1
              with:
                client-id: ${{secrets.AZURE_CLIENT_ID }}
                subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID }}
                tenant-id: ${{secrets.AZURE_TENANT_ID }}
            
            - name: Initialize Terraform
              working-directory: ${{ env.TerraformWorkingDirectory }}
              run: |
                  terraform init \
                      -backend-config=resource_group_name=${{ vars.STATE_RESOURCE_GROUP_NAME}} \
                      -backend-config=storage_account_name=${{ vars.STORAGE_ACCOUNT_NAME }} \
                      -backend-config=container_name=${{ env.StateStoreContainerName }} \
                      -backend-config=key=${{ env.StateStoreFilename }}
              env:
               ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
               ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID  }}
               ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
               ARM_USE_OIDC: true
            
            - name: Plan Terraform
              working-directory: ${{ env.TerraformWorkingDirectory }}
              run: terraform plan -out=tf_plan --var-file="terraform.tfvars"
              env:
                 ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
                 ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID  }}
                 ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
                 ARM_USE_OIDC: true
                 
            - name: Apply Terraform
              id: vnetInfo
              working-directory: ${{ env.TerraformWorkingDirectory }}
              run: |
                 terraform apply -auto-approve tf_plan
                 echo vnetId=$(terraform output vnetId) >> $GITHUB_OUTPUT
                 echo runnerSubnetId=$(terraform output runnerSubnetId) >> $GITHUB_OUTPUT
                 echo resourceGroupName=$(terraform output resourceGroupName) >> $GITHUB_OUTPUT
              env:
                 ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
                 ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID  }}
                 ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
                 ARM_USE_OIDC: true
    deploy-runners:
      needs: deploy-environment
      runs-on: 'ubuntu-latest'
      env:
        TerraformWorkingDirectory: 'src/infra/terraform/runners/aks'
        StateStoreContainerName: 'tfstate'
        StateStoreFilename: 'runners.tfstate'
      steps:
            - uses: actions/checkout@v3
            
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_wrapper: false
            
            - name: Azure login
              uses: azure/login@v1
              with:
                client-id: ${{secrets.AZURE_CLIENT_ID }}
                subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID }}
                tenant-id: ${{secrets.AZURE_TENANT_ID }}
            
            - name: Initialize Terraform
              working-directory: ${{ env.TerraformWorkingDirectory }}
              run: |
                  terraform init \
                      -backend-config=resource_group_name=${{ vars.STATE_RESOURCE_GROUP_NAME}} \
                      -backend-config=storage_account_name=${{ vars.STORAGE_ACCOUNT_NAME }} \
                      -backend-config=container_name=${{ env.StateStoreContainerName }} \
                      -backend-config=key=${{ env.StateStoreFilename }}
              env:
               ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
               ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID  }}
               ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
               ARM_USE_OIDC: true
            
            - name: Plan Terraform
              working-directory: ${{ env.TerraformWorkingDirectory }}
              run: terraform plan -out=tf_plan -var stateSaContainerName=${{ env.StateStoreContainerName }} -var stateSaName=${{ vars.STORAGE_ACCOUNT_NAME }} -var stateSaRg=${{ vars.STATE_RESOURCE_GROUP_NAME }}
              env:
                 ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
                 ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID  }}
                 ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
                 ARM_USE_OIDC: true
                 
            - name: Apply Terraform
              id: clusterInfo
              working-directory: ${{ env.TerraformWorkingDirectory }}
              run: |
                 terraform apply -auto-approve tf_plan
                 echo resourceGroupName=$(terraform output -raw resourceGroupName) >> $GITHUB_OUTPUT
                 echo clusterName=$(terraform output -raw clusterName) >> $GITHUB_OUTPUT
              env:
                 ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
                 ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID  }}
                 ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
                 ARM_USE_OIDC: true

           # Set the target Azure Kubernetes Service (AKS) cluster. 
            - name: Set AKS context
              uses: azure/aks-set-context@v3
              with:
                cluster-name: ${{ steps.clusterInfo.outputs.clusterName }}
                resource-group: ${{ steps.clusterInfo.outputs.resourceGroupName }}

            - name: Install runner 
              working-directory: 'src/manifests'
              run: |
                helm repo add actions-runner-controller https://actions-runner-controller.github.io/actions-runner-controller
                helm upgrade --install --namespace actions-runner-system --create-namespace --wait actions-runner-controller actions-runner-controller/actions-runner-controller --set "githubWebhookServer.enabled=true,service.type=NodePort,githubWebhookServer.ports[0].nodePort=33080"
                kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.8.2/cert-manager.yaml
                kubectl apply -f https://github.com/actions/actions-runner-controller/releases/download/v0.22.0/actions-runner-controller.yaml --server-side
                if [ $(kubectl get secret controller-manager -n actions-runner-system --output='name') != 'secret/controller-manager' ]; then
                        kubectl create secret generic controller-manager -n actions-runner-system --from-literal=github_token=${{ secrets.GH_PAT }}
                fi
                kubectl apply -f runnerdeployment.yaml
